import { Inter } from "next/font/google";
import "@/styles/globals.css"
import ClientLayout from "./ClientLayout";
import ProtectedRoute from "@/components/ProtectRoute";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by Heptagon",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} ` }>    
      <ProtectedRoute>         
            <ClientLayout>{children}</ClientLayout>
      </ProtectedRoute>
      </body>
    </html> 
  );
}
